### ISSUE TITLE
Not a zip file

### ISSUE THREAD

**Issue by mspeculatrix** [nedlir/OfficerBreaker#1]
I tried renaming a .docx file created on a Mac to .zip, but not zip utility I could find would open it. I tried on macOS, Win11 and Linux.

**Comment by nedlir** [comment]
Hi [mspeculatrix](https://github.com/mspeculatrix),

I'm not sure why you changed the` .docx` to `.zip`. My guess is that you try to open the `.docx` file to see its anatomy structure. If that's the case then 7zip should be good enough for this task on all platforms.

If the source code is not working then please attach the file you made to a new issue and I'll give it a look.
