### ISSUE TITLE
Not working with latest .docx files

### ISSUE THREAD

**Issue by zylch11** [nedlir/OfficerBreaker#4]
The latest version of .docx files which are password protected don't have a settings.xml file. The code is also not compatible with JDK 17 and above due to high coupling with nio.
![image](https://user-images.githubusercontent.com/29079254/199096198-0817d3a6-21ff-4825-8692-79b966167937.png)

**Comment by nedlir** [comment]
OfficerBreaker was tested with latest ".docx" files as well on 3 different OS(s). The repository is not supposed to work with password protected files, but rather with read-only protected files.

Maybe I will make a CLI version to avoid FX versions difference.
